export default Object.freeze({
    ENTITY_CLASS_MY_SHIP: 1,
    ENTITY_CLASS_ENEMY_SHIP: 2,
    ENTITY_CLASS_ASTEROID: 3,
    ENTITY_CLASS_MY_SHOT: 4,
    ENTITY_CLASS_ENEMY_SHOT: 5,
    ENTITY_CLASS_MISSILE: 6,
    ENTITY_CLASS_LOOTBOX: 7,
});
